### ISSUE TITLE
Leftover .old files in 0.101002

### ISSUE THREAD

**Issue by perlpunk** [shlomif/Pod-AsciiDoctor#2]
When maintaining openSUSE's perl modules https://build.opensuse.org/project/show/devel:languages:perl I stumbled over these two leftover files:
* Build.PL.old
* README.old

**Comment by shlomif** [comment]
On Mon, 13 Feb 2023 04:35:54 -0800
Tina Müller (tinita) ***@***.***> wrote:

> When maintaining openSUSE's perl modules
> https://build.opensuse.org/project/show/devel:languages:perl I stumbled over
> these two leftover files:
> * Build.PL.old
> * README.old
> 

Hi Tina! i didnt want2completely lose their history. 

-- 

Shlomi Fish       https://www.shlomifish.org/
https://youtu.be/GoEn1YfYTBM - Tiffany Alvord - “Fall Together”

A horse! A horse! My kingdom for a horse!
    — https://en.wikiquote.org/wiki/Richard_III_%28play%29

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by perlpunk** [comment]
> Hi Tina! i didnt want2completely lose their history.

Ok. I would recommend not to package them in the distribution though :)
It looks like we just have to skip `.old` files in our script.

**Comment by shlomif** [comment]
@perlpunk - hi, please try 0.101003.

**Comment by perlpunk** [comment]
thank you! :)
